/* automatically generated by rust-bindgen 0.72.1 */

pub const ECS_QUERY_TERM_CAPACITY: u32 = 64;
pub const ECS_SYSTEM_AFTER_CAPACITY: u32 = 16;
pub const EcsOnAdd: u32 = 0;
pub const EcsOnRemove: u32 = 1;
pub const EcsOnSet: u32 = 2;
#[repr(C)]
#[repr(align(8))]
#[derive(Debug, Copy, Clone)]
pub struct sireflect_struct_desc_t {
    pub _bindgen_opaque_blob: [u64; 4usize],
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of sireflect_struct_desc_t"]
        [::core::mem::size_of::<sireflect_struct_desc_t>() - 32usize];
    ["Alignment of sireflect_struct_desc_t"]
        [::core::mem::align_of::<sireflect_struct_desc_t>() - 8usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_world_s {
    _unused: [u8; 0],
}
pub type ecs_world_t = ecs_world_s;
pub type ecs_entity_t = u64;
pub type ecs_component_t = u16;
pub type ecs_query_id_t = u16;
pub type ecs_system_id_t = u16;
pub type ecs_event_t = u16;
pub type ecs_module_id_t = u16;
pub type ecs_resource_t = u16;
pub type ecs_observer_id_t = u32;
pub type ecs_module_import_t = ::core::option::Option<
    unsafe extern "C" fn(world: *mut ecs_world_t, desc: *const ::core::ffi::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_module_desc_t {
    pub name: *const ::core::ffi::c_char,
    pub id: *mut ecs_module_id_t,
    pub import: ecs_module_import_t,
    pub desc: *const ::core::ffi::c_void,
    pub desc_size: u32,
    pub disabled: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_module_desc_t"][::core::mem::size_of::<ecs_module_desc_t>() - 40usize];
    ["Alignment of ecs_module_desc_t"][::core::mem::align_of::<ecs_module_desc_t>() - 8usize];
    ["Offset of field: ecs_module_desc_t::name"]
        [::core::mem::offset_of!(ecs_module_desc_t, name) - 0usize];
    ["Offset of field: ecs_module_desc_t::id"]
        [::core::mem::offset_of!(ecs_module_desc_t, id) - 8usize];
    ["Offset of field: ecs_module_desc_t::import"]
        [::core::mem::offset_of!(ecs_module_desc_t, import) - 16usize];
    ["Offset of field: ecs_module_desc_t::desc"]
        [::core::mem::offset_of!(ecs_module_desc_t, desc) - 24usize];
    ["Offset of field: ecs_module_desc_t::desc_size"]
        [::core::mem::offset_of!(ecs_module_desc_t, desc_size) - 32usize];
    ["Offset of field: ecs_module_desc_t::disabled"]
        [::core::mem::offset_of!(ecs_module_desc_t, disabled) - 36usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_observer_event_t {
    pub world: *mut ecs_world_t,
    pub entity: ecs_entity_t,
    pub event: ecs_event_t,
    pub user_data: usize,
    pub trigger_data: *const ::core::ffi::c_void,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_observer_event_t"][::core::mem::size_of::<ecs_observer_event_t>() - 40usize];
    ["Alignment of ecs_observer_event_t"][::core::mem::align_of::<ecs_observer_event_t>() - 8usize];
    ["Offset of field: ecs_observer_event_t::world"]
        [::core::mem::offset_of!(ecs_observer_event_t, world) - 0usize];
    ["Offset of field: ecs_observer_event_t::entity"]
        [::core::mem::offset_of!(ecs_observer_event_t, entity) - 8usize];
    ["Offset of field: ecs_observer_event_t::event"]
        [::core::mem::offset_of!(ecs_observer_event_t, event) - 16usize];
    ["Offset of field: ecs_observer_event_t::user_data"]
        [::core::mem::offset_of!(ecs_observer_event_t, user_data) - 24usize];
    ["Offset of field: ecs_observer_event_t::trigger_data"]
        [::core::mem::offset_of!(ecs_observer_event_t, trigger_data) - 32usize];
};
pub type ecs_observer_callback_t =
    ::core::option::Option<unsafe extern "C" fn(event: *mut ecs_observer_event_t)>;
pub type ecs_component_on_add_t = ::core::option::Option<
    unsafe extern "C" fn(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        component: ecs_component_t,
        value: *mut ::core::ffi::c_void,
    ),
>;
pub type ecs_component_on_set_t = ::core::option::Option<
    unsafe extern "C" fn(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        component: ecs_component_t,
        new_value: *const ::core::ffi::c_void,
        current_value: *mut ::core::ffi::c_void,
    ),
>;
pub type ecs_component_on_remove_t = ::core::option::Option<
    unsafe extern "C" fn(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        component: ecs_component_t,
        value: *mut ::core::ffi::c_void,
    ),
>;
pub type ecs_type_ctor_t =
    ::core::option::Option<unsafe extern "C" fn(dst: *mut ::core::ffi::c_void, count: u32)>;
pub type ecs_type_dtor_t =
    ::core::option::Option<unsafe extern "C" fn(ptr: *mut ::core::ffi::c_void, count: u32)>;
pub type ecs_type_copy_t = ::core::option::Option<
    unsafe extern "C" fn(
        dst: *mut ::core::ffi::c_void,
        src: *const ::core::ffi::c_void,
        count: u32,
    ),
>;
pub type ecs_type_move_t = ::core::option::Option<
    unsafe extern "C" fn(dst: *mut ::core::ffi::c_void, src: *mut ::core::ffi::c_void, count: u32),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_type_ops_t {
    pub ctor: ecs_type_ctor_t,
    pub dtor: ecs_type_dtor_t,
    pub copy_ctor: ecs_type_copy_t,
    pub copy: ecs_type_copy_t,
    pub move_ctor: ecs_type_move_t,
    pub move_: ecs_type_move_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_type_ops_t"][::core::mem::size_of::<ecs_type_ops_t>() - 48usize];
    ["Alignment of ecs_type_ops_t"][::core::mem::align_of::<ecs_type_ops_t>() - 8usize];
    ["Offset of field: ecs_type_ops_t::ctor"]
        [::core::mem::offset_of!(ecs_type_ops_t, ctor) - 0usize];
    ["Offset of field: ecs_type_ops_t::dtor"]
        [::core::mem::offset_of!(ecs_type_ops_t, dtor) - 8usize];
    ["Offset of field: ecs_type_ops_t::copy_ctor"]
        [::core::mem::offset_of!(ecs_type_ops_t, copy_ctor) - 16usize];
    ["Offset of field: ecs_type_ops_t::copy"]
        [::core::mem::offset_of!(ecs_type_ops_t, copy) - 24usize];
    ["Offset of field: ecs_type_ops_t::move_ctor"]
        [::core::mem::offset_of!(ecs_type_ops_t, move_ctor) - 32usize];
    ["Offset of field: ecs_type_ops_t::move_"]
        [::core::mem::offset_of!(ecs_type_ops_t, move_) - 40usize];
};
pub const ecs_relation_flags_t_EcsRelationTarget: ecs_relation_flags_t = 1;
pub const ecs_relation_flags_t_EcsRelationSource: ecs_relation_flags_t = 2;
pub const ecs_relation_flags_t_EcsRelationCascadeDelete: ecs_relation_flags_t = 4;
pub const ecs_relation_flags_t_EcsRelationOneToOne: ecs_relation_flags_t = 8;
pub const ecs_relation_flags_t_EcsRelationOneToMany: ecs_relation_flags_t = 16;
pub type ecs_relation_flags_t = ::core::ffi::c_uint;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_component_desc_t {
    pub name: *const ::core::ffi::c_char,
    pub size: u64,
    pub ops: ecs_type_ops_t,
    pub on_set: ecs_component_on_set_t,
    pub on_remove: ecs_component_on_remove_t,
    pub on_add: ecs_component_on_add_t,
    pub relation_flags: u32,
    pub struct_desc: *const sireflect_struct_desc_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_component_desc_t"][::core::mem::size_of::<ecs_component_desc_t>() - 104usize];
    ["Alignment of ecs_component_desc_t"][::core::mem::align_of::<ecs_component_desc_t>() - 8usize];
    ["Offset of field: ecs_component_desc_t::name"]
        [::core::mem::offset_of!(ecs_component_desc_t, name) - 0usize];
    ["Offset of field: ecs_component_desc_t::size"]
        [::core::mem::offset_of!(ecs_component_desc_t, size) - 8usize];
    ["Offset of field: ecs_component_desc_t::ops"]
        [::core::mem::offset_of!(ecs_component_desc_t, ops) - 16usize];
    ["Offset of field: ecs_component_desc_t::on_set"]
        [::core::mem::offset_of!(ecs_component_desc_t, on_set) - 64usize];
    ["Offset of field: ecs_component_desc_t::on_remove"]
        [::core::mem::offset_of!(ecs_component_desc_t, on_remove) - 72usize];
    ["Offset of field: ecs_component_desc_t::on_add"]
        [::core::mem::offset_of!(ecs_component_desc_t, on_add) - 80usize];
    ["Offset of field: ecs_component_desc_t::relation_flags"]
        [::core::mem::offset_of!(ecs_component_desc_t, relation_flags) - 88usize];
    ["Offset of field: ecs_component_desc_t::struct_desc"]
        [::core::mem::offset_of!(ecs_component_desc_t, struct_desc) - 96usize];
};
pub type ecs_resource_hook_t = ::core::option::Option<
    unsafe extern "C" fn(world: *mut ecs_world_t, ptr: *const ::core::ffi::c_void),
>;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_resource_desc_t {
    pub name: *const ::core::ffi::c_char,
    pub size: u64,
    pub ops: ecs_type_ops_t,
    pub on_set: ecs_resource_hook_t,
    pub on_remove: ecs_resource_hook_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_resource_desc_t"][::core::mem::size_of::<ecs_resource_desc_t>() - 80usize];
    ["Alignment of ecs_resource_desc_t"][::core::mem::align_of::<ecs_resource_desc_t>() - 8usize];
    ["Offset of field: ecs_resource_desc_t::name"]
        [::core::mem::offset_of!(ecs_resource_desc_t, name) - 0usize];
    ["Offset of field: ecs_resource_desc_t::size"]
        [::core::mem::offset_of!(ecs_resource_desc_t, size) - 8usize];
    ["Offset of field: ecs_resource_desc_t::ops"]
        [::core::mem::offset_of!(ecs_resource_desc_t, ops) - 16usize];
    ["Offset of field: ecs_resource_desc_t::on_set"]
        [::core::mem::offset_of!(ecs_resource_desc_t, on_set) - 64usize];
    ["Offset of field: ecs_resource_desc_t::on_remove"]
        [::core::mem::offset_of!(ecs_resource_desc_t, on_remove) - 72usize];
};
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ecs_term_access_t {
    In = 0,
    Out = 1,
    InOut = 2,
    InOptional = 3,
    InOutOptional = 4,
    Filter = 5,
    Not = 6,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_query_term_t {
    pub id: ecs_component_t,
    pub access: ecs_term_access_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_query_term_t"][::core::mem::size_of::<ecs_query_term_t>() - 8usize];
    ["Alignment of ecs_query_term_t"][::core::mem::align_of::<ecs_query_term_t>() - 4usize];
    ["Offset of field: ecs_query_term_t::id"]
        [::core::mem::offset_of!(ecs_query_term_t, id) - 0usize];
    ["Offset of field: ecs_query_term_t::access"]
        [::core::mem::offset_of!(ecs_query_term_t, access) - 4usize];
};
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_query_desc_t {
    pub terms: [ecs_query_term_t; 64usize],
    pub is_a: ecs_entity_t,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_query_desc_t"][::core::mem::size_of::<ecs_query_desc_t>() - 520usize];
    ["Alignment of ecs_query_desc_t"][::core::mem::align_of::<ecs_query_desc_t>() - 8usize];
    ["Offset of field: ecs_query_desc_t::terms"]
        [::core::mem::offset_of!(ecs_query_desc_t, terms) - 0usize];
    ["Offset of field: ecs_query_desc_t::is_a"]
        [::core::mem::offset_of!(ecs_query_desc_t, is_a) - 512usize];
};
unsafe extern "C" {
    pub fn ecs_init() -> *mut ecs_world_t;
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_world_feat_desc_t {
    pub rest: bool,
    pub target_fps: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_world_feat_desc_t"][::core::mem::size_of::<ecs_world_feat_desc_t>() - 4usize];
    ["Alignment of ecs_world_feat_desc_t"]
        [::core::mem::align_of::<ecs_world_feat_desc_t>() - 2usize];
    ["Offset of field: ecs_world_feat_desc_t::rest"]
        [::core::mem::offset_of!(ecs_world_feat_desc_t, rest) - 0usize];
    ["Offset of field: ecs_world_feat_desc_t::target_fps"]
        [::core::mem::offset_of!(ecs_world_feat_desc_t, target_fps) - 2usize];
};
unsafe extern "C" {
    pub fn ecs_init_w_features(features: *const ecs_world_feat_desc_t) -> *mut ecs_world_t;
}
unsafe extern "C" {
    pub fn ecs_fini(world: *mut ecs_world_t);
}
unsafe extern "C" {
    pub fn ecs_quit(world: *mut ecs_world_t);
}
unsafe extern "C" {
    pub fn ecs_module_init(
        world: *mut ecs_world_t,
        desc: *const ecs_module_desc_t,
    ) -> ecs_module_id_t;
}
unsafe extern "C" {
    pub fn ecs_module_find(world: *mut ecs_world_t, id: *const ecs_module_id_t) -> ecs_module_id_t;
}
unsafe extern "C" {
    pub fn ecs_module_enable(world: *mut ecs_world_t, module: ecs_module_id_t);
}
unsafe extern "C" {
    pub fn ecs_module_disable(world: *mut ecs_world_t, module: ecs_module_id_t);
}
unsafe extern "C" {
    pub fn ecs_module_is_enabled(world: *const ecs_world_t, module: ecs_module_id_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_component_init(
        world: *mut ecs_world_t,
        desc: *const ecs_component_desc_t,
    ) -> ecs_component_t;
}
unsafe extern "C" {
    pub fn ecs_component_register(
        world: *mut ecs_world_t,
        id: *mut ecs_component_t,
        desc: *const ecs_component_desc_t,
    ) -> ecs_component_t;
}
unsafe extern "C" {
    pub fn ecs_new(world: *mut ecs_world_t) -> ecs_entity_t;
}
unsafe extern "C" {
    pub fn ecs_defer_begin(world: *mut ecs_world_t);
}
unsafe extern "C" {
    pub fn ecs_defer_end(world: *mut ecs_world_t);
}
unsafe extern "C" {
    pub fn ecs_is_deferred(world: *const ecs_world_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_is_alive(world: *const ecs_world_t, entity: ecs_entity_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_is(world: *mut ecs_world_t, entity: ecs_entity_t, target: ecs_entity_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_is_a(world: *mut ecs_world_t, entity: ecs_entity_t, target: ecs_entity_t);
}
unsafe extern "C" {
    pub fn ecs_kill(world: *mut ecs_world_t, entity: ecs_entity_t);
}
unsafe extern "C" {
    pub fn ecs_query_init(
        world: *mut ecs_world_t,
        query: *const ecs_query_desc_t,
    ) -> ecs_query_id_t;
}
unsafe extern "C" {
    pub fn ecs_query_fini(world: *mut ecs_world_t, qid: ecs_query_id_t);
}
unsafe extern "C" {
    pub fn ecs_add_cid(world: *mut ecs_world_t, entity: ecs_entity_t, id: ecs_component_t);
}
unsafe extern "C" {
    pub fn ecs_remove_cid(world: *mut ecs_world_t, entity: ecs_entity_t, id: ecs_component_t);
}
unsafe extern "C" {
    pub fn ecs_has_cid(
        world: *const ecs_world_t,
        entity: ecs_entity_t,
        id: ecs_component_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ecs_has_cid_owned(
        world: *const ecs_world_t,
        entity: ecs_entity_t,
        id: ecs_component_t,
    ) -> bool;
}
unsafe extern "C" {
    pub fn ecs_get_cid(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        id: ecs_component_t,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn ecs_try_get_cid(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        cid: ecs_component_t,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn ecs_set_cid(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        id: ecs_component_t,
        data: *const ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn ecs_move_cid(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        id: ecs_component_t,
        data: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn ecs_resource_init(
        world: *mut ecs_world_t,
        desc: *const ecs_resource_desc_t,
    ) -> ecs_resource_t;
}
unsafe extern "C" {
    pub fn ecs_resource_register(
        world: *mut ecs_world_t,
        id: *mut ecs_resource_t,
        desc: *const ecs_resource_desc_t,
    ) -> ecs_resource_t;
}
unsafe extern "C" {
    pub fn ecs_resource_find(
        world: *mut ecs_world_t,
        name: *const ::core::ffi::c_char,
    ) -> ecs_resource_t;
}
unsafe extern "C" {
    pub fn ecs_resource_is_registered_rid(world: *const ecs_world_t, id: ecs_resource_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_set_resource_rid(
        world: *mut ecs_world_t,
        id: ecs_resource_t,
        data: *const ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn ecs_move_resource_rid(
        world: *mut ecs_world_t,
        id: ecs_resource_t,
        data: *mut ::core::ffi::c_void,
    );
}
unsafe extern "C" {
    pub fn ecs_resource_rid(
        world: *mut ecs_world_t,
        id: ecs_resource_t,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn ecs_try_resource_rid(
        world: *mut ecs_world_t,
        id: ecs_resource_t,
    ) -> *mut ::core::ffi::c_void;
}
unsafe extern "C" {
    pub fn ecs_has_resource_rid(world: *const ecs_world_t, id: ecs_resource_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_remove_resource_rid(world: *mut ecs_world_t, id: ecs_resource_t);
}
unsafe extern "C" {
    pub fn ecs_with(world: *mut ecs_world_t, component: ecs_component_t, require: ecs_component_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_observer_desc_t {
    pub on: ecs_event_t,
    pub query: ecs_query_desc_t,
    pub callback: ecs_observer_callback_t,
    pub user_data: usize,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_observer_desc_t"][::core::mem::size_of::<ecs_observer_desc_t>() - 544usize];
    ["Alignment of ecs_observer_desc_t"][::core::mem::align_of::<ecs_observer_desc_t>() - 8usize];
    ["Offset of field: ecs_observer_desc_t::on"]
        [::core::mem::offset_of!(ecs_observer_desc_t, on) - 0usize];
    ["Offset of field: ecs_observer_desc_t::query"]
        [::core::mem::offset_of!(ecs_observer_desc_t, query) - 8usize];
    ["Offset of field: ecs_observer_desc_t::callback"]
        [::core::mem::offset_of!(ecs_observer_desc_t, callback) - 528usize];
    ["Offset of field: ecs_observer_desc_t::user_data"]
        [::core::mem::offset_of!(ecs_observer_desc_t, user_data) - 536usize];
};
unsafe extern "C" {
    pub fn ecs_event(world: *mut ecs_world_t) -> ecs_event_t;
}
unsafe extern "C" {
    pub fn ecs_event_register(world: *mut ecs_world_t, id: *mut ecs_event_t) -> ecs_event_t;
}
unsafe extern "C" {
    pub fn ecs_observer_init(
        world: *mut ecs_world_t,
        desc: *const ecs_observer_desc_t,
    ) -> ecs_observer_id_t;
}
unsafe extern "C" {
    pub fn ecs_observer_enable(world: *mut ecs_world_t, id: ecs_observer_id_t);
}
unsafe extern "C" {
    pub fn ecs_observer_disable(world: *mut ecs_world_t, id: ecs_observer_id_t);
}
unsafe extern "C" {
    pub fn ecs_observer_trigger(
        world: *mut ecs_world_t,
        entity: ecs_entity_t,
        event: ecs_event_t,
        trigger_data: *const ::core::ffi::c_void,
    );
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ecs_field_kind_t {
    None = 0,
    Owned = 1,
    Shared = 2,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_iter_t {
    pub world: *mut ecs_world_t,
    pub count: u32,
    pub entities: *mut ecs_entity_t,
    pub ptrs: *mut *mut ::core::ffi::c_void,
    pub delta_time: f32,
    pub cache: *mut ecs_query_cache_s,
    pub field_kinds: *mut ecs_field_kind_t,
    pub user_data: usize,
    pub table_idx: u16,
    pub table_count: u16,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_iter_t"][::core::mem::size_of::<ecs_iter_t>() - 72usize];
    ["Alignment of ecs_iter_t"][::core::mem::align_of::<ecs_iter_t>() - 8usize];
    ["Offset of field: ecs_iter_t::world"][::core::mem::offset_of!(ecs_iter_t, world) - 0usize];
    ["Offset of field: ecs_iter_t::count"][::core::mem::offset_of!(ecs_iter_t, count) - 8usize];
    ["Offset of field: ecs_iter_t::entities"]
        [::core::mem::offset_of!(ecs_iter_t, entities) - 16usize];
    ["Offset of field: ecs_iter_t::ptrs"][::core::mem::offset_of!(ecs_iter_t, ptrs) - 24usize];
    ["Offset of field: ecs_iter_t::delta_time"]
        [::core::mem::offset_of!(ecs_iter_t, delta_time) - 32usize];
    ["Offset of field: ecs_iter_t::cache"][::core::mem::offset_of!(ecs_iter_t, cache) - 40usize];
    ["Offset of field: ecs_iter_t::field_kinds"]
        [::core::mem::offset_of!(ecs_iter_t, field_kinds) - 48usize];
    ["Offset of field: ecs_iter_t::user_data"]
        [::core::mem::offset_of!(ecs_iter_t, user_data) - 56usize];
    ["Offset of field: ecs_iter_t::table_idx"]
        [::core::mem::offset_of!(ecs_iter_t, table_idx) - 64usize];
    ["Offset of field: ecs_iter_t::table_count"]
        [::core::mem::offset_of!(ecs_iter_t, table_count) - 66usize];
};
unsafe extern "C" {
    pub fn ecs_query_iter(world: *mut ecs_world_t, query_id: ecs_query_id_t) -> ecs_iter_t;
}
unsafe extern "C" {
    pub fn ecs_iter_next(it: *mut ecs_iter_t) -> bool;
}
#[repr(u32)]
#[derive(Debug, Copy, Clone, Hash, PartialEq, Eq)]
pub enum ecs_phase_t {
    PreStart = 0,
    Start = 1,
    PostStart = 2,
    OnLoad = 3,
    PostLoad = 4,
    PreUpdate = 5,
    OnUpdate = 6,
    PostUpdate = 7,
    PreRender = 8,
    OnRender = 9,
    PostRender = 10,
    PhaseCount = 11,
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_system_desc_t {
    pub name: *const ::core::ffi::c_char,
    pub query: ecs_query_desc_t,
    pub callback: ::core::option::Option<unsafe extern "C" fn(arg1: *mut ecs_iter_t)>,
    pub user_data: usize,
    pub user_data_dtor: ::core::option::Option<unsafe extern "C" fn(user_data: usize)>,
    pub phase: ecs_phase_t,
    pub after: [ecs_system_id_t; 16usize],
    pub disabled: bool,
}
#[allow(clippy::unnecessary_operation, clippy::identity_op)]
const _: () = {
    ["Size of ecs_system_desc_t"][::core::mem::size_of::<ecs_system_desc_t>() - 592usize];
    ["Alignment of ecs_system_desc_t"][::core::mem::align_of::<ecs_system_desc_t>() - 8usize];
    ["Offset of field: ecs_system_desc_t::name"]
        [::core::mem::offset_of!(ecs_system_desc_t, name) - 0usize];
    ["Offset of field: ecs_system_desc_t::query"]
        [::core::mem::offset_of!(ecs_system_desc_t, query) - 8usize];
    ["Offset of field: ecs_system_desc_t::callback"]
        [::core::mem::offset_of!(ecs_system_desc_t, callback) - 528usize];
    ["Offset of field: ecs_system_desc_t::user_data"]
        [::core::mem::offset_of!(ecs_system_desc_t, user_data) - 536usize];
    ["Offset of field: ecs_system_desc_t::user_data_dtor"]
        [::core::mem::offset_of!(ecs_system_desc_t, user_data_dtor) - 544usize];
    ["Offset of field: ecs_system_desc_t::phase"]
        [::core::mem::offset_of!(ecs_system_desc_t, phase) - 552usize];
    ["Offset of field: ecs_system_desc_t::after"]
        [::core::mem::offset_of!(ecs_system_desc_t, after) - 556usize];
    ["Offset of field: ecs_system_desc_t::disabled"]
        [::core::mem::offset_of!(ecs_system_desc_t, disabled) - 588usize];
};
unsafe extern "C" {
    pub fn ecs_system_init(
        world: *mut ecs_world_t,
        desc: *const ecs_system_desc_t,
    ) -> ecs_system_id_t;
}
unsafe extern "C" {
    pub fn ecs_progress(world: *mut ecs_world_t) -> bool;
}
unsafe extern "C" {
    pub fn ecs_run_phase(world: *mut ecs_world_t, phase: ecs_phase_t);
}
unsafe extern "C" {
    pub fn ecs_run_system(world: *mut ecs_world_t, system: ecs_system_id_t);
}
unsafe extern "C" {
    pub fn ecs_system_enable(world: *mut ecs_world_t, system: ecs_system_id_t);
}
unsafe extern "C" {
    pub fn ecs_system_disable(world: *mut ecs_world_t, system: ecs_system_id_t);
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct ecs_query_cache_s {
    pub _address: u8,
}
