#!/usr/bin/env sh
set -eu

root=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
shader_directory="$root/shaders"
output="$root/src/sigpu_shaders.generated.h"
temporary_directory=$(mktemp -d "${TMPDIR:-/tmp}/sigpu-shaders.XXXXXX")
temporary_output=$(mktemp "$root/src/.sigpu_shaders.generated.XXXXXX")

cleanup() {
    rm -rf "$temporary_directory"
    rm -f "$temporary_output"
}
trap cleanup EXIT HUP INT TERM

command -v glslc >/dev/null 2>&1 || {
    echo "sigpu: glslc is required to compile shaders" >&2
    exit 1
}
command -v xxd >/dev/null 2>&1 || {
    echo "sigpu: xxd is required to embed shaders" >&2
    exit 1
}

for source in "$shader_directory"/*.vert "$shader_directory"/*.frag; do
    [ -f "$source" ] || continue
    glslc "$source" -o "$temporary_directory/$(basename -- "$source").spv"
done

{
    cat <<'HEADER'
/* Generated by tools/embed_shaders.sh. Do not edit manually. */
#ifndef SIGPU_SHADERS_GENERATED_H
#define SIGPU_SHADERS_GENERATED_H

#include <stddef.h>
#include <stdint.h>
#include <string.h>

typedef struct {
    const char *name;
    const uint8_t *code;
    size_t size;
} sigpu_embedded_shader_t;

HEADER

    for shader in "$temporary_directory"/*.spv; do
        [ -f "$shader" ] || continue
        symbol=$(basename -- "$shader" | tr '.-' '__')
        xxd -i -n "sigpu_shader_${symbol}" "$shader" |
            sed -e 's/^unsigned char /static const uint8_t /' -e '/^unsigned int .*_len = /d'
        printf "\n"
    done

    cat <<'TABLE'
static const sigpu_embedded_shader_t sigpu_embedded_shaders[] = {
TABLE
    for shader in "$temporary_directory"/*.spv; do
        [ -f "$shader" ] || continue
        name=$(basename -- "$shader")
        symbol=$(printf '%s' "$name" | tr '.-' '__')
        printf '    { "%s", sigpu_shader_%s, sizeof(sigpu_shader_%s) },\n' "$name" "$symbol" "$symbol"
    done
    cat <<'FOOTER'
};

static const sigpu_embedded_shader_t *sigpu_embedded_shader_find(const char *name) {
    for (size_t index = 0; index < sizeof(sigpu_embedded_shaders) / sizeof(*sigpu_embedded_shaders);
         index++) {
        if (strcmp(name, sigpu_embedded_shaders[index].name) == 0)
            return &sigpu_embedded_shaders[index];
    }
    return NULL;
}

#endif
FOOTER
} >"$temporary_output"

mv "$temporary_output" "$output"
