[package]
name = "siecs"
version = "0.1.0"
edition = "2021"
links = "siecs"
description = "Rust bindings for SIECS"
license = "MIT"
repository = "https://github.com/suleymanlaarabi/siecs"

[workspace]
members = ["siecs_derive"]

[dependencies]
siecs_derive = { path = "siecs_derive", version = "0.1.0" }
variadics_please = "2.0.0"

[build-dependencies]
cc = "1"
