#include <siui.h>
#include <bake_test.h>
#include <math.h>
#include <stdlib.h>
#include <string.h>
static void start(void) { ecs_init();ECS_MODULE_IMPORT(siui,{.gpu=false}); }
static void finish(void) { ecs_fini(); }
static ecs_entity_t node(UiNode desc) { ecs_entity_t e=ecs_new();ecs_set_cid(e,ecs_id(UiNode),&desc);return e; }
static const UiComputedLayout *layout(ecs_entity_t e) {siui_layout_update(800,600);return siui_layout(e);}
static void near(float want,float got) {test_assert(fabsf(want-got)<0.01f);}
void layout_auto_empty(void) {start();ecs_entity_t e=node((UiNode){0});near(0,layout(e)->width);near(0,layout(e)->height);finish();}
void layout_auto_text(void) {start();ecs_entity_t e=node((UiNode){0});test_true(siui_set_text(e,"Hello",5));test_true(layout(e)->width>0);test_true(layout(e)->height>0);finish();}
void layout_text_grows(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Hi",2);float before=layout(e)->width;siui_set_text(e,"Hello world, this is longer",27);test_true(layout(e)->width>before);finish();}
void layout_max_width_wrap(void) {start();ecs_entity_t e=node((UiNode){.max_width=siui_px(100)});siui_set_text(e,"A long phrase that has many words",33);test_true(layout(e)->width<=100);finish();}
void layout_wrap_height(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"A long phrase that has many words",33);float before=layout(e)->height;ecs_set(e,UiNode,{.max_width=siui_px(80)});test_true(layout(e)->height>before);finish();}
void layout_min_max(void) {start();ecs_entity_t e=node((UiNode){.width=siui_px(500),.height=siui_px(5),.min_height=siui_px(20),.max_width=siui_px(400)});near(400,layout(e)->width);near(20,layout(e)->height);ecs_set(e,UiNode,{.width=siui_px(5),.height=siui_px(500),.min_width=siui_px(20),.max_height=siui_px(400)});near(20,layout(e)->width);near(400,layout(e)->height);finish();}
void layout_padding(void) {start();ecs_entity_t e=node((UiNode){.padding=siui_all(10)});near(20,layout(e)->width);near(20,layout(e)->height);finish();}
void layout_four_borders(void) {start();ecs_entity_t e=node((UiNode){.border_width=siui_trbl(1,2,3,4)});near(6,layout(e)->width);near(4,layout(e)->height);finish();}
void layout_parent_child_auto(void) {start();ecs_entity_t p=node((UiNode){0}),c=node((UiNode){.width=siui_px(120),.height=siui_px(30)});ecs_relate(c,ChildOf,p);near(120,layout(p)->width);near(30,layout(p)->height);finish();}
void layout_row_column(void) {start();ecs_entity_t p=node((UiNode){.direction=SIUI_ROW,.gap=5}),a=node((UiNode){.width=siui_px(10),.height=siui_px(20)}),b=node((UiNode){.width=siui_px(30),.height=siui_px(40)});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);near(45,layout(p)->width);near(40,layout(p)->height);ecs_set(p,UiNode,{.direction=SIUI_COLUMN,.gap=5});near(30,layout(p)->width);near(65,layout(p)->height);finish();}
void layout_grow_shrink(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(100),.height=siui_px(20),.direction=SIUI_ROW}),a=node((UiNode){.width=siui_px(20),.height=siui_px(10),.flex_grow=1}),b=node((UiNode){.width=siui_px(20),.height=siui_px(10),.flex_grow=1});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);near(50,layout(a)->width);near(50,layout(b)->width);ecs_set(p,UiNode,{.width=siui_px(30),.height=siui_px(20),.direction=SIUI_ROW});ecs_set(a,UiNode,{.width=siui_px(20),.height=siui_px(10),.flex_shrink=1});ecs_set(b,UiNode,{.width=siui_px(20),.height=siui_px(10),.flex_shrink=1});near(15,layout(a)->width);finish();}
void layout_wrap(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(50),.direction=SIUI_ROW,.wrap=SIUI_WRAP}),a=node((UiNode){.width=siui_px(40),.height=siui_px(10)}),b=node((UiNode){.width=siui_px(40),.height=siui_px(10)});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);test_true(layout(b)->y>=10);near(20,siui_layout(p)->height);finish();}
void layout_justify_align_stretch(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(100),.height=siui_px(50),.direction=SIUI_ROW,.justify=SIUI_CENTER,.align_items=SIUI_STRETCH}),a=node((UiNode){.width=siui_px(20)});ecs_relate(a,ChildOf,p);near(40,layout(a)->x);near(50,layout(a)->height);finish();}
void layout_percentages(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(200),.height=siui_px(100),.padding=siui_all(10)}),c=node((UiNode){.width=siui_percent(50),.height=siui_percent(50)});ecs_relate(c,ChildOf,p);near(90,layout(c)->width);near(40,layout(c)->height);finish();}
void layout_absolute(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(200),.height=siui_px(100)}),c=node((UiNode){.width=siui_px(30),.height=siui_px(20),.position=SIUI_ABSOLUTE,.right=siui_px(5),.bottom=siui_px(10)});ecs_relate(c,ChildOf,p);near(165,layout(c)->x);near(70,layout(c)->y);finish();}
void layout_nested_auto(void) {start();ecs_entity_t a=node((UiNode){.padding=siui_all(1)}),b=node((UiNode){.padding=siui_all(2)}),c=node((UiNode){.width=siui_px(10)});ecs_relate(b,ChildOf,a);ecs_relate(c,ChildOf,b);near(16,layout(a)->width);finish();}
void layout_overflow_hidden(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(50),.height=siui_px(20),.padding=siui_all(5),.overflow=SIUI_HIDDEN}),c=node((UiNode){.width=siui_px(100),.height=siui_px(10)});ecs_relate(c,ChildOf,p);near(40,layout(c)->clip_width);near(40,siui_layout(p)->clip_width);finish();}
void layout_childof_runtime(void) {start();ecs_entity_t p=node((UiNode){0}),c=node((UiNode){.width=siui_px(30)});near(0,layout(p)->width);ecs_relate(c,ChildOf,p);near(30,layout(p)->width);ecs_unrelate(c,ChildOf);near(0,layout(p)->width);finish();}
void layout_text_runtime(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Hi",2);float first=layout(e)->width;siui_set_text(e,"Longer text",11);test_true(layout(e)->width>first);finish();}
void layout_resize(void) {start();ecs_entity_t e=node((UiNode){.width=siui_percent(50)});siui_layout_update(800,600);near(400,siui_layout(e)->width);siui_layout_update(400,600);near(200,siui_layout(e)->width);finish();}
void layout_utf8(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Héllö 世界",strlen("Héllö 世界"));test_true(layout(e)->width>0);finish();}
void layout_empty_text(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"",0);near(0,layout(e)->width);finish();}
void layout_order(void) {start();ecs_entity_t p=node((UiNode){.direction=SIUI_ROW}),a=node((UiNode){.width=siui_px(10),.order=2}),b=node((UiNode){.width=siui_px(10),.order=1});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);layout(a);test_true(siui_layout(b)->x<siui_layout(a)->x);finish();}
void layout_order_runtime(void) {start();ecs_entity_t p=node((UiNode){.direction=SIUI_ROW}),a=node((UiNode){.width=siui_px(10)}),b=node((UiNode){.width=siui_px(10)});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);layout(a);ecs_set(a,UiNode,{.width=siui_px(10),.order=2});ecs_set(b,UiNode,{.width=siui_px(10),.order=1});layout(a);test_true(siui_layout(b)->x<siui_layout(a)->x);finish();}
void layout_deep_tree(void) {start();ecs_entity_t p=node((UiNode){0}),root=p;for(int i=0;i<2000;i++){ecs_entity_t c=node((UiNode){.padding=siui_all(1)});ecs_relate(c,ChildOf,p);p=c;}test_not_null((void *)layout(root));near(4000,siui_layout(root)->width);finish();}
void layout_many_siblings(void) {start();ecs_entity_t p=node((UiNode){.direction=SIUI_ROW});for(int i=0;i<3000;i++){ecs_entity_t c=node((UiNode){.width=siui_px(1)});ecs_relate(c,ChildOf,p);}near(3000,layout(p)->width);finish();}
void layout_static_clean(void) {start();ecs_entity_t e=node((UiNode){.width=siui_px(10)});layout(e);test_false(siui_layout_update(800,600));near(0,(float)siui_stats().measured_nodes);finish();}
void layout_paint_only(void) {start();ecs_entity_t e=node((UiNode){.width=siui_px(10)});layout(e);uint64_t generation=siui_stats().generation;ecs_set(e,UiPaint,{.background={1,2,3,255}});test_false(siui_layout_update(800,600));test_uint(generation,siui_stats().generation);finish();}
void layout_reparent(void) {start();ecs_entity_t p=node((UiNode){0}),q=node((UiNode){0}),c=node((UiNode){.width=siui_px(30)});ecs_relate(c,ChildOf,p);near(30,layout(p)->width);ecs_relate(c,ChildOf,q);near(0,layout(p)->width);near(30,siui_layout(q)->width);finish();}
void layout_font_size_runtime(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Hello",5);float before=layout(e)->width;UiText text=*ecs_get(e,UiText);text.font_size=32;ecs_set_cid(e,ecs_id(UiText),&text);test_true(layout(e)->width>before);finish();}
void layout_auto_parent_percent(void) {start();ecs_entity_t p=node((UiNode){.direction=SIUI_COLUMN}),fixed=node((UiNode){.width=siui_px(200)}),relative=node((UiNode){.width=siui_percent(50)});ecs_relate(fixed,ChildOf,p);ecs_relate(relative,ChildOf,p);near(200,layout(p)->width);near(100,siui_layout(relative)->width);finish();}
void layout_aspect_ratio(void) {start();ecs_entity_t e=node((UiNode){.width=siui_px(100),.aspect_ratio=2});near(50,layout(e)->height);finish();}
void layout_align_content(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(50),.height=siui_px(100),.direction=SIUI_ROW,.wrap=SIUI_WRAP,.align_content=SIUI_ALIGN_END}),a=node((UiNode){.width=siui_px(40),.height=siui_px(10)}),b=node((UiNode){.width=siui_px(40),.height=siui_px(10)});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);near(80,layout(a)->y);near(90,siui_layout(b)->y);finish();}
void layout_space_between(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(100),.direction=SIUI_ROW,.justify=SIUI_SPACE_BETWEEN}),a=node((UiNode){.width=siui_px(20)}),b=node((UiNode){.width=siui_px(20)});ecs_relate(a,ChildOf,p);ecs_relate(b,ChildOf,p);near(0,layout(a)->x);near(80,siui_layout(b)->x);ecs_set(p,UiNode,{.width=siui_px(100),.direction=SIUI_ROW,.justify=SIUI_SPACE_AROUND,.gap=10});near(12.5f,layout(a)->x);ecs_set(p,UiNode,{.width=siui_px(100),.direction=SIUI_ROW,.justify=SIUI_SPACE_EVENLY,.gap=10});near(50.0f/3.0f,layout(a)->x);finish();}
void layout_margin(void) {start();ecs_entity_t p=node((UiNode){0}),c=node((UiNode){.width=siui_px(10),.height=siui_px(4),.margin=siui_trbl(2,7,3,5)});ecs_relate(c,ChildOf,p);near(22,layout(p)->width);near(9,siui_layout(p)->height);near(5,siui_layout(c)->x);near(2,siui_layout(c)->y);finish();}
void layout_line_height(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Hello\nworld",11);float first=layout(e)->height;UiText style=*ecs_get(e,UiText);style.line_height=2;ecs_set_cid(e,ecs_id(UiText),&style);test_true(layout(e)->height>first);finish();}
void layout_text_cleared(void) {start();ecs_entity_t e=node((UiNode){0});siui_set_text(e,"Hello",5);test_true(layout(e)->width>0);siui_set_text(e,"",0);near(0,layout(e)->width);near(0,layout(e)->height);finish();}
void layout_overflow_runtime(void) {start();ecs_entity_t p=node((UiNode){.width=siui_px(50),.height=siui_px(20),.padding=siui_all(5)}),c=node((UiNode){.width=siui_px(100)});ecs_relate(c,ChildOf,p);near(800,layout(c)->clip_width);ecs_set(p,UiNode,{.width=siui_px(50),.height=siui_px(20),.padding=siui_all(5),.overflow=SIUI_HIDDEN});near(40,layout(c)->clip_width);finish();}
