#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RUST_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd -- "$RUST_ROOT/../.." && pwd)"
VENDOR_DIR="$RUST_ROOT/vendor"
DIST_DIR="$REPO_ROOT/distr"

if [ ! -s "$DIST_DIR/siecs.c" ] || [ ! -s "$DIST_DIR/siecs.h" ]; then
    echo 'missing distr/siecs.c or distr/siecs.h; run `make distr` first' >&2
    exit 1
fi

rm -rf "$VENDOR_DIR"
mkdir -p "$VENDOR_DIR"

cp "$DIST_DIR/siecs.c" "$VENDOR_DIR/siecs.c"
cp "$DIST_DIR/siecs.h" "$VENDOR_DIR/siecs.h"

cat > "$VENDOR_DIR/README.md" <<'README'
# Generated vendor snapshot

This directory is generated by `bindings/siecs_rust/tools/update_vendor.sh`.

Do not edit files here manually.

The Rust crate vendors only the standalone `distr/siecs.c` and `distr/siecs.h`
snapshot. Run `make distr` before updating this directory.
README

echo "Updated $VENDOR_DIR"
