#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
RUST_ROOT="$(cd -- "$SCRIPT_DIR/.." && pwd)"
REPO_ROOT="$(cd -- "$RUST_ROOT/../.." && pwd)"
VENDOR_DIR="$RUST_ROOT/vendor"
WORK_DIR="$(mktemp -d)"

cleanup() {
    rm -rf "$WORK_DIR"
}
trap cleanup EXIT

copy_tree() {
    local src="$1"
    local dst="$2"

    mkdir -p "$dst"
    cp -R "$src"/. "$dst"/
}

copy_dependency() {
    local name="$1"
    local repo="$2"
    local src="$WORK_DIR/$name"
    local dst="$VENDOR_DIR/deps/$name"

    git clone --depth 1 "$repo" "$src"

    copy_tree "$src/include" "$dst/include"
    copy_tree "$src/src" "$dst/src"

    if [ -f "$src/LICENSE" ]; then
        cp "$src/LICENSE" "$dst/LICENSE"
    fi
}

rm -rf "$VENDOR_DIR"
mkdir -p "$VENDOR_DIR/siecs" "$VENDOR_DIR/deps"

copy_tree "$REPO_ROOT/include" "$VENDOR_DIR/siecs/include"
copy_tree "$REPO_ROOT/src" "$VENDOR_DIR/siecs/src"

copy_dependency "sireflect" "https://github.com/suleymanlaarabi/sireflect.git"
copy_dependency "sijson" "https://github.com/suleymanlaarabi/sijson.git"
copy_dependency "sihttp" "https://github.com/suleymanlaarabi/sihttp.git"

mkdir -p "$VENDOR_DIR/siecs/deps"
cp "$VENDOR_DIR/deps/sireflect/include/sireflect.h" "$VENDOR_DIR/siecs/deps/sireflect.h"
cp "$VENDOR_DIR/deps/sijson/include/sijson.h" "$VENDOR_DIR/siecs/deps/sijson.h"
cp "$VENDOR_DIR/deps/sihttp/include/sihttp.h" "$VENDOR_DIR/siecs/deps/sihttp.h"

cat > "$VENDOR_DIR/README.md" <<'README'
# Generated vendor snapshot

This directory is generated by `bindings/siecs_rust/tools/update_vendor.sh`.

Do not edit files here manually.

The script always vendors the latest default branch of the official dependency
repositories, and snapshots the current SIECS source tree from the repository
root.
README

echo "Updated $VENDOR_DIR"
