// Comment out this line when using as DLL
#define siecs_cpp_STATIC
#ifndef SIECS_CPP_H
#define SIECS_CPP_H

#ifdef __cplusplus
#ifndef SIECS_CPP_HPP
#define SIECS_CPP_HPP

/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SIECS_CPP_BAKE_CONFIG_H
#define SIECS_CPP_BAKE_CONFIG_H

/* Headers of public dependencies */
#include "siecs.h"

/* Convenience macro for exporting symbols */
#ifndef siecs_cpp_STATIC
#if defined(siecs_cpp_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define SIECS_CPP_API __declspec(dllexport)
#elif defined(siecs_cpp_EXPORTS)
  #define SIECS_CPP_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define SIECS_CPP_API __declspec(dllimport)
#else
  #define SIECS_CPP_API
#endif
#else
  #define SIECS_CPP_API
#endif

#endif

#pragma once
#pragma once

#include "siecs.h"
#pragma once
#include <string_view>

namespace ecs {

template <class T> consteval std::string_view type_name() {
#if defined(__clang__)
    constexpr std::string_view prefix = "std::string_view type_name() [T = ";
    constexpr std::string_view suffix = "]";
    constexpr std::string_view func = __PRETTY_FUNCTION__;
#elif defined(__GNUC__)
    constexpr std::string_view prefix = "consteval std::string_view type_name() [with T = ";
    constexpr std::string_view suffix = "]";
    constexpr std::string_view func = __PRETTY_FUNCTION__;
#else
#error "type_name<T>() only supports GCC and Clang"
#endif

    constexpr auto start = prefix.size();
    constexpr auto end = func.size() - suffix.size();
    return func.substr(start, end - start);
}

} // namespace ecs

#include <new>
#include <string>
#include <type_traits>

namespace ecs {

template <typename T, typename = void> struct is_complete : std::false_type {};

template <typename T> struct is_complete<T, std::void_t<decltype(sizeof(T))>> : std::true_type {};

template <typename T> constexpr size_t sisizeof() {
    if constexpr (is_complete<T>::value) {
        return sizeof(T);
    } else {
        return 0;
    }
}

template <typename T> static ecs_component_t ecs_cpp_component_id(ecs_world_t *world) {
    static ecs_component_t cid = 0;

    if (cid != 0) {
        return cid;
    }

    std::string name = std::string(type_name<T>());

    ecs_component_desc_t desc = {
        .name = name.c_str(),
        .size = sisizeof<T>(),
        .on_remove =
            [](ecs_world_t *world, ecs_entity_t, ecs_component_t, const void *ptr) {
                static_cast<const T *>(ptr)->~T();
            },
        .on_add =
            [](ecs_world_t *world, ecs_entity_t, ecs_component_t, const void *ptr) {
                new (const_cast<void *>(ptr)) T();
            },
        .struct_desc = NULL,
    };

    cid = ecs_component_init(world, &desc);

    return cid;
}

} // namespace ecs

#pragma once
#include "siecs.h"

namespace ecs {

class entity {
    ecs_entity_t _entity;
    ecs_world_t *_world;

  public:
    entity(ecs_world_t *world, ecs_entity_t entity) : _entity(entity), _world(world) {}

    template <typename T> entity add() {
        ecs_add_cid(_world, _entity, ecs_cpp_component_id<T>(_world));
        return *this;
    }

    template <typename T> entity set(const T &value) {
        ecs_set_cid(_world, _entity, ecs_cpp_component_id<T>(_world), &value);
        return *this;
    }
};

} // namespace ecs

#include "siecs.h"

namespace ecs {

class world {
    ecs_world_t *_world;

  public:
    world() : _world(ecs_init()) {}

    template <typename T> ecs_component_t component() { return ecs_cpp_component_id<T>(_world); }

    ecs::entity entity() { return ecs::entity(_world, ecs_new(_world)); }
};

} // namespace ecs

#endif

#endif

#endif

