// Comment out this line when using as DLL
#define siecs_cpp_STATIC
#ifndef SIECS_CPP_H
#define SIECS_CPP_H

#ifdef __cplusplus
#ifndef SIECS_CPP_HPP
#define SIECS_CPP_HPP

/*
                                   )
                                  (.)
                                  .|.
                                  | |
                              _.--| |--._
                           .-';  ;`-'& ; `&.
                          \   &  ;    &   &_/
                           |"""---...---"""|
                           \ | | | | | | | /
                            `---.|.|.|.---'

 * This file is generated by bake.lang.c for your convenience. Headers of
 * dependencies will automatically show up in this file. Include bake_config.h
 * in your main project file. Do not edit! */

#ifndef SIECS_CPP_BAKE_CONFIG_H
#define SIECS_CPP_BAKE_CONFIG_H

/* Headers of public dependencies */
#include "siecs.h"

/* Convenience macro for exporting symbols */
#ifndef siecs_cpp_STATIC
#if defined(siecs_cpp_EXPORTS) && (defined(_MSC_VER) || defined(__MINGW32__))
  #define SIECS_CPP_API __declspec(dllexport)
#elif defined(siecs_cpp_EXPORTS)
  #define SIECS_CPP_API __attribute__((__visibility__("default")))
#elif defined(_MSC_VER)
  #define SIECS_CPP_API __declspec(dllimport)
#else
  #define SIECS_CPP_API
#endif
#else
  #define SIECS_CPP_API
#endif

#endif

#pragma once
#pragma once

#include "siecs.h"
#pragma once
#include <string_view>
#include <tuple>
#include <type_traits>
#include <utility>

namespace ecs {

template <class T> consteval std::string_view type_name() {
#if defined(__clang__)
    constexpr std::string_view prefix = "std::string_view type_name() [T = ";
    constexpr std::string_view suffix = "]";
    constexpr std::string_view func = __PRETTY_FUNCTION__;
#elif defined(__GNUC__)
    constexpr std::string_view prefix = "consteval std::string_view type_name() [with T = ";
    constexpr std::string_view suffix = "]";
    constexpr std::string_view func = __PRETTY_FUNCTION__;
#else
#error "type_name<T>() only supports GCC and Clang"
#endif

    constexpr auto start = prefix.size();
    constexpr auto end = func.size() - suffix.size();
    return func.substr(start, end - start);
}

template <typename T> struct function_traits;

// function pointer
template <typename R, typename... Args> struct function_traits<R (*)(Args...)> {
    using return_type = R;
    using args_tuple = std::tuple<Args...>;
};

// function reference
template <typename R, typename... Args> struct function_traits<R (&)(Args...)> {
    using return_type = R;
    using args_tuple = std::tuple<Args...>;
};

// member function pointer const
template <typename C, typename R, typename... Args>
struct function_traits<R (C::*)(Args...) const> {
    using return_type = R;
    using args_tuple = std::tuple<Args...>;
};

// member function pointer non-const
template <typename C, typename R, typename... Args> struct function_traits<R (C::*)(Args...)> {
    using return_type = R;
    using args_tuple = std::tuple<Args...>;
};

// lambda / functor
template <typename F>
struct function_traits : function_traits<decltype(&std::remove_reference_t<F>::operator())> {};

template <typename Tuple, typename Fn, std::size_t... I>
constexpr void for_each_type_impl(Fn &&fn, std::index_sequence<I...>) {
    (fn.template operator()<std::tuple_element_t<I, Tuple>>(), ...);
}

template <typename Tuple, typename Fn> constexpr void for_each_type(Fn &&fn) {
    constexpr std::size_t N = std::tuple_size_v<Tuple>;
    for_each_type_impl<Tuple>(std::forward<Fn>(fn), std::make_index_sequence<N>{});
}

} // namespace ecs

#include <new>
#include <string>
#include <type_traits>

namespace ecs {

template <typename T, typename = void> struct is_complete : std::false_type {};

template <typename T> struct is_complete<T, std::void_t<decltype(sizeof(T))>> : std::true_type {};

template <typename T> constexpr size_t sisizeof() {
    if constexpr (is_complete<T>::value) {
        return sizeof(T);
    } else {
        return 0;
    }
}

template <typename T> static ecs_component_t ecs_cpp_component_id(ecs_world_t *world) {
    static ecs_component_t cid = 0;

    if (cid != 0) {
        return cid;
    }

    std::string name = std::string(type_name<T>());

    ecs_component_desc_t desc = {
        .name = name.c_str(),
        .size = sisizeof<T>(),
        .on_set = nullptr,
        .on_remove = []([[maybe_unused]] ecs_world_t *world,
                        [[maybe_unused]] ecs_entity_t entity,
                        [[maybe_unused]] ecs_component_t component,
                        const void *ptr) { static_cast<const T *>(ptr)->~T(); },
        .on_add = []([[maybe_unused]] ecs_world_t *world,
                     [[maybe_unused]] ecs_entity_t entity,
                     [[maybe_unused]] ecs_component_t component,
                     const void *ptr) { new (const_cast<void *>(ptr)) T(); },
        .is_relation = false,
        .struct_desc = nullptr,
    };

    cid = ecs_component_init(world, &desc);

    return cid;
}

} // namespace ecs

#pragma once
#include "siecs.h"

namespace ecs {

class entity {
    ecs_entity_t _entity;
    ecs_world_t *_world;

  public:
    static ecs::entity null() { return entity(nullptr, 0); }

    entity(ecs_world_t *world, ecs_entity_t entity) : _entity(entity), _world(world) {}

    template <typename T> entity add() {
        ecs_add_cid(_world, _entity, ecs_cpp_component_id<T>(_world));
        return *this;
    }

    template <typename T> entity set(const T &value) {
        ecs_set_cid(_world, _entity, ecs_cpp_component_id<T>(_world), &value);
        return *this;
    }
};

} // namespace ecs

#pragma once

#include "siecs.h"
#include <cstdint>
#include <functional>
#include <tuple>
#include <type_traits>
#include <utility>

namespace ecs {

template <typename F, typename Tuple, std::size_t... Is>
inline void call_fields_impl(F &&func, Tuple &fields, uint32_t count, std::index_sequence<Is...>) {
    for (uint32_t i = 0; i < count; ++i) {
        std::invoke(std::forward<F>(func), (std::get<Is>(fields)[i])...);
    }
}

template <typename F, typename Tuple>
inline void call_fields(F &&func, Tuple &fields, uint32_t count) {
    constexpr std::size_t N = std::tuple_size_v<std::remove_reference_t<Tuple>>;

    call_fields_impl(std::forward<F>(func), fields, count, std::make_index_sequence<N>{});
}

template <typename Args, std::size_t... Is>
auto make_fields(ecs_iter_t *it, std::index_sequence<Is...>) {
    return std::tuple{ static_cast<std::remove_reference_t<std::tuple_element_t<Is, Args>> *>(
        ecs_field(it, static_cast<uint16_t>(Is))
    )... };
}

template <typename T> consteval ecs_term_access_t term_access() {
    static_assert(
        std::is_lvalue_reference_v<T>,
        "query callback arguments must be lvalue references"
    );

    if constexpr (std::is_const_v<std::remove_reference_t<T>>) {
        return EcsIn;
    } else {
        return EcsInOut;
    }
}

class world;

class query {
    ecs_query_desc_t desc{};
    uint16_t term_index = 0;
    ecs_world_t *_world = nullptr;

  public:
    explicit query(ecs_world_t *world) noexcept : _world(world) {}

    template <typename... T> query &&require() {

        (
            [&] {
                desc.terms[term_index].id = ecs::ecs_cpp_component_id<T>(_world);
                desc.terms[term_index].access = EcsFilter;
                term_index += 1;
            }(),
            ...);

        return std::move(*this);
    }

    template <typename... T> query &&exclude() {

        (
            [&] {
                desc.terms[term_index].id = ecs::ecs_cpp_component_id<T>(_world);
                desc.terms[term_index].access = EcsNot;
                term_index += 1;
            }(),
            ...);

        return std::move(*this);
    }

    template <typename F> void each(F &&func) {
        using traits = function_traits<std::remove_reference_t<F>>;
        using args = typename traits::args_tuple;
        constexpr std::size_t arg_count = std::tuple_size_v<args>;
        static_assert(arg_count > 0, "query callbacks must read at least one component");

        for_each_type<args>([&]<typename T>() {
            desc.terms[term_index].id = ecs::ecs_cpp_component_id<std::remove_cvref_t<T>>(_world);
            desc.terms[term_index].access = term_access<T>();
            term_index += 1;
        });

        ecs_query_id_t qid = ecs_query_init(_world, &desc);
        ecs_iter_t it = ecs_query_iter(_world, qid);

        while (ecs_iter_next(&it)) {
            auto fields = make_fields<args>(&it, std::make_index_sequence<arg_count>{});

            call_fields(std::forward<F>(func), fields, it.count);
        }

        ecs_query_fini(_world, qid);
    }

    void first() { return; }
};

} // namespace ecs

#include "siecs.h"
#include <utility>

namespace ecs {

class world {
    ecs_world_t *_world = nullptr;

  public:
    world() noexcept : _world(ecs_init()) {}
    explicit world(ecs_world_t *world) noexcept : _world(world) {}

    world(const world &) = delete;
    world &operator=(const world &) = delete;

    world(world &&other) noexcept : _world(std::exchange(other._world, nullptr)) {}

    world &operator=(world &&other) noexcept {
        if (this != &other) {
            reset();
            _world = std::exchange(other._world, nullptr);
        }

        return *this;
    }

    ~world() noexcept { reset(); }

    [[nodiscard]] ecs_world_t *c_ptr() const noexcept { return _world; }

    void reset(ecs_world_t *world = nullptr) noexcept {
        if (_world != nullptr) {
            ecs_fini(_world);
        }

        _world = world;
    }

    template <typename T> [[nodiscard]] ecs_component_t component() const {
        return ecs_cpp_component_id<T>(_world);
    }

    [[nodiscard]] ecs::entity entity() const { return ecs::entity(_world, ecs_new(_world)); }
    [[nodiscard]] ecs::query query() const { return ecs::query(_world); }
};

} // namespace ecs

#endif

#endif

#endif

